### ISSUE TITLE
Embedded Fonts? 

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/Media-Player#6]
I'd like to figure out if I can embed Fonts so that the UI is rendered consistently across different platforms. Not sure if this is possible, or if it would even make a difference.

**Comment by israel-dryer** [comment]
Just try using the default Font.

https://tkdocs.com/tutorial/fonts.html

**Comment by MikeTheWatchGuy** [comment]
I thought I documented the list of fonts that tkinter offers. It will map the settings or name of the font to the correct font that is available on that platform. There are a fewest number of fonts that should fill your need that will work in tkinter, Qt, Etc
You could do what I did on the opencv ASCII webcam demo program. I had font settings and other GUI framework specific settings on the same line as the import statement. This allowed me to comment and uncomment a single line of code and get all of the settings for that GUI platform in that one statement so that the rest of the code did not need to change

**Comment by israel-dryer** [comment]
I've been using `sg.DEFAULT_FONT` whenever I need to make size or style adjustments.
